name: Publish Nuget Package

on:
  push:
    tags:
       - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  publish:
    runs-on : ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '9.0.x'

        - name: Restore dependencies
          run: dotnet restore

        - name: Build the project
          run: dotnet build --configuration Release --no-restore

        - name: Pack the project
          run: |
            # Strip the 'v' prefix from the tag to get the version number
            VERSION=$(echo $GITHUB_REF_NAME | sed 's/^v//')
            dotnet pack --configuration Release --no-build --output ./nupkg -p:PackageVersion=$VERSION

        - name: Publish to NuGet
          env:
            NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          run: dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
